//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindIt.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindIt.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 One of the properties must have a value. 的本地化字符串。
        /// </summary>
        internal static string AtLeastOneNonNullPropertyValidationAttribute_IsValid_OnePropertyMustHaveValue {
            get {
                return ResourceManager.GetString("AtLeastOneNonNullPropertyValidationAttribute_IsValid_OnePropertyMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New User 的本地化字符串。
        /// </summary>
        internal static string AuthController_CreateOrGetUser_New_User {
            get {
                return ResourceManager.GetString("AuthController_CreateOrGetUser_New_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We are unable to authenticate you with provider at this time.  Please check your provider URL and try again. 的本地化字符串。
        /// </summary>
        internal static string AuthController_SignIn_UnableToAuthenticateWithProvider {
            get {
                return ResourceManager.GetString("AuthController_SignIn_UnableToAuthenticateWithProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to authenticate at this time. 的本地化字符串。
        /// </summary>
        internal static string AuthController_SignInResponse_Unable_to_authenticate {
            get {
                return ResourceManager.GetString("AuthController_SignInResponse_Unable_to_authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find vehicle to update. 的本地化字符串。
        /// </summary>
        internal static string CannotFindVehicleToUpdateExceptionMessage {
            get {
                return ResourceManager.GetString("CannotFindVehicleToUpdateExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Average Fuel Efficiency 的本地化字符串。
        /// </summary>
        internal static string ChartController_AverageFuelEfficiencyChart_Title {
            get {
                return ResourceManager.GetString("ChartController_AverageFuelEfficiencyChart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Cost 的本地化字符串。
        /// </summary>
        internal static string ChartController_TotalCost_Title {
            get {
                return ResourceManager.GetString("ChartController_TotalCost_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Distance 的本地化字符串。
        /// </summary>
        internal static string ChartController_TotalDistance_Title {
            get {
                return ResourceManager.GetString("ChartController_TotalDistance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The due distance must be greater than the current odometer of {0}. 的本地化字符串。
        /// </summary>
        internal static string DueDistanceNotGreaterThanOdometer {
            get {
                return ResourceManager.GetString("DueDistanceNotGreaterThanOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost Per Unit 的本地化字符串。
        /// </summary>
        internal static string FillupEntryCostPerUnitLabelText {
            get {
                return ResourceManager.GetString("FillupEntryCostPerUnitLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date is required. 的本地化字符串。
        /// </summary>
        internal static string FillupEntryDateRequired {
            get {
                return ResourceManager.GetString("FillupEntryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fuel Efficiency 的本地化字符串。
        /// </summary>
        internal static string FillupEntryFuelEfficiencyLabelText {
            get {
                return ResourceManager.GetString("FillupEntryFuelEfficiencyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The odometer must be between 1 and 1,000,000. 的本地化字符串。
        /// </summary>
        internal static string FillupEntryOdometerRangeValidationError {
            get {
                return ResourceManager.GetString("FillupEntryOdometerRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Odometer is required. 的本地化字符串。
        /// </summary>
        internal static string FillupEntryOdometerRequired {
            get {
                return ResourceManager.GetString("FillupEntryOdometerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price Per Unit (ex. 3.75) 的本地化字符串。
        /// </summary>
        internal static string FillupEntryPricePerUnitLabelText {
            get {
                return ResourceManager.GetString("FillupEntryPricePerUnitLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The price per gallon must be between 0.1 and 100. 的本地化字符串。
        /// </summary>
        internal static string FillupEntryPricePerUnitRangeValidationError {
            get {
                return ResourceManager.GetString("FillupEntryPricePerUnitRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price per unit is required. 的本地化字符串。
        /// </summary>
        internal static string FillupEntryPricePerUnitRequired {
            get {
                return ResourceManager.GetString("FillupEntryPricePerUnitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remarks must be fewer than 250 characters. 的本地化字符串。
        /// </summary>
        internal static string FillupEntryRemarksStringLengthValidationError {
            get {
                return ResourceManager.GetString("FillupEntryRemarksStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Cost 的本地化字符串。
        /// </summary>
        internal static string FillupEntryTotalCostLabelText {
            get {
                return ResourceManager.GetString("FillupEntryTotalCostLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Fuel Cost 的本地化字符串。
        /// </summary>
        internal static string FillupEntryTotalFuelCostLabelText {
            get {
                return ResourceManager.GetString("FillupEntryTotalFuelCostLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Units (ex. 10.123) 的本地化字符串。
        /// </summary>
        internal static string FillupEntryTotalUnitsLabelText {
            get {
                return ResourceManager.GetString("FillupEntryTotalUnitsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The total gallons must be between 1 and 1000. 的本地化字符串。
        /// </summary>
        internal static string FillupEntryTotalUnitsRangeValidationError {
            get {
                return ResourceManager.GetString("FillupEntryTotalUnitsRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total units are required. 的本地化字符串。
        /// </summary>
        internal static string FillupEntryTotalUnitsRequired {
            get {
                return ResourceManager.GetString("FillupEntryTotalUnitsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction Fee (ex. 0.45) 的本地化字符串。
        /// </summary>
        internal static string FillupEntryTransactionFeeLabelText {
            get {
                return ResourceManager.GetString("FillupEntryTransactionFeeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The transaction fee must be between 0 and 100. 的本地化字符串。
        /// </summary>
        internal static string FillupEntryTransactionFeeRangeValidationError {
            get {
                return ResourceManager.GetString("FillupEntryTransactionFeeRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction fee is required. 的本地化字符串。
        /// </summary>
        internal static string FillupEntryTransactionFeeRequired {
            get {
                return ResourceManager.GetString("FillupEntryTransactionFeeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit Of Measure 的本地化字符串。
        /// </summary>
        internal static string FillupEntryUnitOfMeasureLabelText {
            get {
                return ResourceManager.GetString("FillupEntryUnitOfMeasureLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit of measure is required. 的本地化字符串。
        /// </summary>
        internal static string FillUpEntryUnitOfMeasureRequired {
            get {
                return ResourceManager.GetString("FillUpEntryUnitOfMeasureRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill up Station 的本地化字符串。
        /// </summary>
        internal static string FillUpEntryVendorLabelText {
            get {
                return ResourceManager.GetString("FillUpEntryVendorLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill up station must be fewer than 20 characters. 的本地化字符串。
        /// </summary>
        internal static string FillupEntryVendorStringLengthValidationError {
            get {
                return ResourceManager.GetString("FillupEntryVendorStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This date must be a date in the future. 的本地化字符串。
        /// </summary>
        internal static string FutureDateValidationMessage {
            get {
                return ResourceManager.GetString("FutureDateValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^[\d\w]{0,10}$ 的本地化字符串。
        /// </summary>
        internal static string InternationalPostalCodeRegex {
            get {
                return ResourceManager.GetString("InternationalPostalCodeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Postal codes must be alphanumeric and ten characters or less. 的本地化字符串。
        /// </summary>
        internal static string InternationalPostalCodeValidationErrorMessage {
            get {
                return ResourceManager.GetString("InternationalPostalCodeValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only alpha-numeric characters and [.,_-&apos;] are allowed. 的本地化字符串。
        /// </summary>
        internal static string InvalidInputCharacter {
            get {
                return ResourceManager.GetString("InvalidInputCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only alpha-numeric characters, new lines, and [.,_-&apos;] are allowed. 的本地化字符串。
        /// </summary>
        internal static string InvalidMultilineInput {
            get {
                return ResourceManager.GetString("InvalidMultilineInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File uploaded for vehicle photo is not an image or is not a supported image format. 的本地化字符串。
        /// </summary>
        internal static string InvalidVehiclePhoto {
            get {
                return ResourceManager.GetString("InvalidVehiclePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New User 的本地化字符串。
        /// </summary>
        internal static string NewUserDefaultDisplayName {
            get {
                return ResourceManager.GetString("NewUserDefaultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The odometer must be greater than the prior value of {0}. 的本地化字符串。
        /// </summary>
        internal static string OdometerNotGreaterThanPrior {
            get {
                return ResourceManager.GetString("OdometerNotGreaterThanPrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This date can not be in the future. 的本地化字符串。
        /// </summary>
        internal static string PastDateValidationMessage {
            get {
                return ResourceManager.GetString("PastDateValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Due Date 的本地化字符串。
        /// </summary>
        internal static string ReminderDueDateLabelText {
            get {
                return ResourceManager.GetString("ReminderDueDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Due when odometer reads 的本地化字符串。
        /// </summary>
        internal static string ReminderDueDistanceLabelText {
            get {
                return ResourceManager.GetString("ReminderDueDistanceLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The odometer due distance must be between 1 and 1,000,000. 的本地化字符串。
        /// </summary>
        internal static string ReminderDueDistanceRangeValidationError {
            get {
                return ResourceManager.GetString("ReminderDueDistanceRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remarks must be fewer than 250 characters. 的本地化字符串。
        /// </summary>
        internal static string ReminderRemarksStringLengthValidationError {
            get {
                return ResourceManager.GetString("ReminderRemarksStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title is required. 的本地化字符串。
        /// </summary>
        internal static string ReminderTitleRequired {
            get {
                return ResourceManager.GetString("ReminderTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title must be fewer than 50 characters. 的本地化字符串。
        /// </summary>
        internal static string ReminderTitleStringLengthValidationError {
            get {
                return ResourceManager.GetString("ReminderTitleStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date must be between {0:d} and {1:d}. 的本地化字符串。
        /// </summary>
        internal static string StoreRestrictedDateValidationMessage {
            get {
                return ResourceManager.GetString("StoreRestrictedDateValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^(?!.*--)[A-Za-z0-9\.,&apos;_ \-]*$ 的本地化字符串。
        /// </summary>
        internal static string TextLineInputValidatorRegEx {
            get {
                return ResourceManager.GetString("TextLineInputValidatorRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^(?!.*--)([A-Za-z0-9\.,&apos;_ \-]|\r|\n)*$ 的本地化字符串。
        /// </summary>
        internal static string TextMultilineValidatorRegEx {
            get {
                return ResourceManager.GetString("TextMultilineValidatorRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum number of vehicles is 10. 的本地化字符串。
        /// </summary>
        internal static string TooManyVehicles {
            get {
                return ResourceManager.GetString("TooManyVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to add fill up to vehicle. 的本地化字符串。
        /// </summary>
        internal static string UnableToAddFillupToVehicleExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddFillupToVehicleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to add reminder to vehicle. 的本地化字符串。
        /// </summary>
        internal static string UnableToAddReminderToVehicleExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddReminderToVehicleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create user 的本地化字符串。
        /// </summary>
        internal static string UnableToCreateUserExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToCreateUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create vehicle. 的本地化字符串。
        /// </summary>
        internal static string UnableToCreateVehicleExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToCreateVehicleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to delete reminder. 的本地化字符串。
        /// </summary>
        internal static string UnableToDeleteReminder {
            get {
                return ResourceManager.GetString("UnableToDeleteReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to delete vehicle 的本地化字符串。
        /// </summary>
        internal static string UnableToDeleteVehicleExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteVehicleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find user 的本地化字符串。
        /// </summary>
        internal static string UnableToFindUserExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToFindUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to fulfill reminder. 的本地化字符串。
        /// </summary>
        internal static string UnableToFulfillReminder {
            get {
                return ResourceManager.GetString("UnableToFulfillReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve countries and regions list. 的本地化字符串。
        /// </summary>
        internal static string UnableToGetCountryListExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetCountryListExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get vehicles. 的本地化字符串。
        /// </summary>
        internal static string UnableToGetVehiclesExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetVehiclesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve fill up information 的本地化字符串。
        /// </summary>
        internal static string UnableToRetireveFillupsExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetireveFillupsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve fulfilled reminders 的本地化字符串。
        /// </summary>
        internal static string UnableToRetrieveFulfilledReminders {
            get {
                return ResourceManager.GetString("UnableToRetrieveFulfilledReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve overdue reminders. 的本地化字符串。
        /// </summary>
        internal static string UnableToRetrieveOverdueReminders {
            get {
                return ResourceManager.GetString("UnableToRetrieveOverdueReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retieve reminder. 的本地化字符串。
        /// </summary>
        internal static string UnableToRetrieveReminderExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveReminderExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve service history. 的本地化字符串。
        /// </summary>
        internal static string UnableToRetrieveServiceHistory {
            get {
                return ResourceManager.GetString("UnableToRetrieveServiceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve unfulfilled reminders 的本地化字符串。
        /// </summary>
        internal static string UnableToRetrieveUnfulfilledReminders {
            get {
                return ResourceManager.GetString("UnableToRetrieveUnfulfilledReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve upcoming reminders 的本地化字符串。
        /// </summary>
        internal static string UnableToRetrieveUpcomingReminders {
            get {
                return ResourceManager.GetString("UnableToRetrieveUpcomingReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve vehicle photo. 的本地化字符串。
        /// </summary>
        internal static string UnableToRetrieveVehiclePhoto {
            get {
                return ResourceManager.GetString("UnableToRetrieveVehiclePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to update user. 的本地化字符串。
        /// </summary>
        internal static string UnableToUpdateUserExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to update vehicle 的本地化字符串。
        /// </summary>
        internal static string UnableToUpdateVehicleExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateVehicleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to update vehicle sort order. 的本地化字符串。
        /// </summary>
        internal static string UnableToUpdateVehicleSortOrderExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateVehicleSortOrderExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 United States 的本地化字符串。
        /// </summary>
        internal static string UnitedStatesDisplayString {
            get {
                return ResourceManager.GetString("UnitedStatesDisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenID Url 的本地化字符串。
        /// </summary>
        internal static string UserAuthorizationIdLabelText {
            get {
                return ResourceManager.GetString("UserAuthorizationIdLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization ID is required. 的本地化字符串。
        /// </summary>
        internal static string UserAuthorizationIdRequired {
            get {
                return ResourceManager.GetString("UserAuthorizationIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Country or Region 的本地化字符串。
        /// </summary>
        internal static string UserCountryLabelText {
            get {
                return ResourceManager.GetString("UserCountryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Country must be less than 50 characters. 的本地化字符串。
        /// </summary>
        internal static string UserCountryStringLengthValidationError {
            get {
                return ResourceManager.GetString("UserCountryStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Name 的本地化字符串。
        /// </summary>
        internal static string UserDisplayNameLabelText {
            get {
                return ResourceManager.GetString("UserDisplayNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display name is required. 的本地化字符串。
        /// </summary>
        internal static string UserDisplayNameRequired {
            get {
                return ResourceManager.GetString("UserDisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display name must be less than 15 characters. 的本地化字符串。
        /// </summary>
        internal static string UserDisplayNameStringLengthValidationError {
            get {
                return ResourceManager.GetString("UserDisplayNameStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Postal Code 的本地化字符串。
        /// </summary>
        internal static string UserPostalCodeLabelText {
            get {
                return ResourceManager.GetString("UserPostalCodeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Postal code must be less than 10 characters. 的本地化字符串。
        /// </summary>
        internal static string UserPostalCodeStringLengthValidationError {
            get {
                return ResourceManager.GetString("UserPostalCodeStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^[\d]{5}$ 的本地化字符串。
        /// </summary>
        internal static string USPostalCodeRegex {
            get {
                return ResourceManager.GetString("USPostalCodeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 United States postal codes must be five digit numbers. 的本地化字符串。
        /// </summary>
        internal static string USPostalCodeValidationErrorMessage {
            get {
                return ResourceManager.GetString("USPostalCodeValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully added fill up 的本地化字符串。
        /// </summary>
        internal static string VehicleController_AddFillupSuccessMessage {
            get {
                return ResourceManager.GetString("VehicleController_AddFillupSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The odometer must be greater than the prior value of {0}. 的本地化字符串。
        /// </summary>
        internal static string VehicleController_ValidateCanAdd_OdometerGreaterThanPrior {
            get {
                return ResourceManager.GetString("VehicleController_ValidateCanAdd_OdometerGreaterThanPrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not add vehicle.  The maximum number of vehciles is 10. 的本地化字符串。
        /// </summary>
        internal static string VehicleController_ValidateCreate_TooManyVehicles {
            get {
                return ResourceManager.GetString("VehicleController_ValidateCreate_TooManyVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File uploaded for vehicle photo is not an image or is not a supported image format. 的本地化字符串。
        /// </summary>
        internal static string VehicleController_ValidatePhoto_NotAPhoto {
            get {
                return ResourceManager.GetString("VehicleController_ValidatePhoto_NotAPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The photo uploaded must be less than 1MB (1048576 bytes) 的本地化字符串。
        /// </summary>
        internal static string VehicleController_ValidatePhoto_TooLarge {
            get {
                return ResourceManager.GetString("VehicleController_ValidatePhoto_TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make is not valid. 的本地化字符串。
        /// </summary>
        internal static string VehicleMakeInvalid {
            get {
                return ResourceManager.GetString("VehicleMakeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make 的本地化字符串。
        /// </summary>
        internal static string VehicleMakeLabelText {
            get {
                return ResourceManager.GetString("VehicleMakeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make must be less than 50 characters. 的本地化字符串。
        /// </summary>
        internal static string VehicleMakeStringLengthValidationError {
            get {
                return ResourceManager.GetString("VehicleMakeStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing make for specified model. 的本地化字符串。
        /// </summary>
        internal static string VehicleMissingMakeForModel {
            get {
                return ResourceManager.GetString("VehicleMissingMakeForModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing year for specified make. 的本地化字符串。
        /// </summary>
        internal static string VehicleMissingYearForMake {
            get {
                return ResourceManager.GetString("VehicleMissingYearForMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing year for specified model. 的本地化字符串。
        /// </summary>
        internal static string VehicleMissingYearForModel {
            get {
                return ResourceManager.GetString("VehicleMissingYearForModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model is not valid. 的本地化字符串。
        /// </summary>
        internal static string VehicleModelInvalid {
            get {
                return ResourceManager.GetString("VehicleModelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        internal static string VehicleModelLabelText {
            get {
                return ResourceManager.GetString("VehicleModelLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model must be less than 50 characters. 的本地化字符串。
        /// </summary>
        internal static string VehicleModelStringLengthValidationError {
            get {
                return ResourceManager.GetString("VehicleModelStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vehicle Name 的本地化字符串。
        /// </summary>
        internal static string VehicleNameLabelText {
            get {
                return ResourceManager.GetString("VehicleNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name is required. 的本地化字符串。
        /// </summary>
        internal static string VehicleNameRequired {
            get {
                return ResourceManager.GetString("VehicleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name must be less than 20 characters. 的本地化字符串。
        /// </summary>
        internal static string VehicleNameStringLengthValidationError {
            get {
                return ResourceManager.GetString("VehicleNameStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The vehicle was not found. 的本地化字符串。
        /// </summary>
        internal static string VehicleNotFound {
            get {
                return ResourceManager.GetString("VehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image MIME type is required. 的本地化字符串。
        /// </summary>
        internal static string VehiclePhotoImageMimeTypeRequired {
            get {
                return ResourceManager.GetString("VehiclePhotoImageMimeTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image is required. 的本地化字符串。
        /// </summary>
        internal static string VehiclePhotoImageRequired {
            get {
                return ResourceManager.GetString("VehiclePhotoImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The photo uploaded must be less than 1 MB. 的本地化字符串。
        /// </summary>
        internal static string VehiclePhotoTooLarge {
            get {
                return ResourceManager.GetString("VehiclePhotoTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort Order 的本地化字符串。
        /// </summary>
        internal static string VehicleSortOrderLabelText {
            get {
                return ResourceManager.GetString("VehicleSortOrderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The sort order must be between 0 and 10,000. 的本地化字符串。
        /// </summary>
        internal static string VehicleSortOrderRangeValidationError {
            get {
                return ResourceManager.GetString("VehicleSortOrderRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year is not valid. 的本地化字符串。
        /// </summary>
        internal static string VehicleYearInvalid {
            get {
                return ResourceManager.GetString("VehicleYearInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Year 的本地化字符串。
        /// </summary>
        internal static string VehicleYearLabelText {
            get {
                return ResourceManager.GetString("VehicleYearLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The year must be between 1900 and 2100. 的本地化字符串。
        /// </summary>
        internal static string VehicleYearRangeValidationError {
            get {
                return ResourceManager.GetString("VehicleYearRangeValidationError", resourceCulture);
            }
        }
    }
}
